# Generated by Django 4.1.5 on 2023-01-14 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='tax',
            field=models.CharField(default='0', max_length=244, null=True),
        ),
    ]
